### ISSUE TITLE
Add a Privacy disclaimer to Concordia bot

### ISSUE THREAD

**Issue by sdkonerira** [Concordium/concordium-web3id#133]
**Task description**

Reqest from Jorgen to add the follwoing disclaimer as a popup for Concordiabot: 

**IMPORTANT PRIVACY NOTICE**

Please observe that if you select the "Full name - requires Concordium mainnet identity and account" option, your personal full name on Discord and/or Telegram will be exposed, depending on what social media options you choose.

If you only select the Telegram and Discord options, then only your username from the platform that is used for verification will be exposed on the platform you are verifying. For example, if you are using your Discord profile to verify your Telegram account, your Discord username will be displayed in your Telegram channel upon verification.

The selected information may thus be visible to any person that have access to the communication channel that you use to post messages, including persons that may not be known to you.

Please observe that once your full name or user name has been displayed on the relevant social media platform, the name will remain there permanently. You will not be able to remove this information again.

You may however at any time change your selection of options and in that way disable any future request to show your full name or user ID. But your name or user name will not be deleted from previous communication in the relevant channel / social media platform.

**Sub-tasks**
- [ ] subtask 1
- [ ] subtask 2
- [ ] subtask 3

*Add label for component and priority.*

**Comment by abizjak** [comment]
@rkj see the issue for the disclaimer that should be used in the pop-up.
