### ISSUE TITLE
Add function to revert revoked credentials to issuer frontend

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-web3id#48]
**Task description**
Add function to revert revoked credentials to issuer frontend. Issuer will be able to revert revoked credentials.

I would assume you would basically use the holder_id and press a button to achieve that.

**Sub-tasks**
- [ ] subtask 1
- [ ] subtask 2
- [ ] subtask 3

**Comment by DOBEN** [comment]
close as completed
