### ISSUE TITLE
[Concordia] Add version to frontend

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-web3id#76]
**Task description**

We should add a version to frontend to make it easier to test/see what is being used.

**Comment by mh-concordium** [comment]
@soerenbf When is it planned to implement this task?

**Comment by abizjak** [comment]
@mh-concordium There is a PR already for this, but it is not merged or deployed.

I expect that we will have the version on Monday.

**Comment by abizjak** [comment]
I believe this should also be closed now @mh-concordium right?

**Comment by mh-concordium** [comment]
Yes.
