### ISSUE TITLE
Enable attempt to issue credentials with invalid attribute

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-web3id#79]
**Description**
After issuer has been created, it should be possible to try to issue credentials with an unrecognized attribute type. Currently this is limited because frontend validates against valid attribute types (string/number/integer and date-time).

For example if the issuers schema has a type X and I try t issue credentials using that type, the frontend would not be able to recognize that as int, string or date so it would just send a string that will be in the field for type X.

**Versions**
- Software Version: 1.0.9

**Comment by abizjak** [comment]
This is fixed in 1.0.10 version.

Or at least it "should" be, I have not tested it since it's complex to set up.
