### ISSUE TITLE
Web3 ID Issuer Testing Front End

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-web3id#8]
**Task description**

The front end should have two flows:
- An issuer should be able to deploy a new smart contract instance of the `credential_registry_smart_contract`.
- This issuer should be able to issue new credentials by invoking the corresponding function in the `credential_registry_smart_contract`.

Only the browser wallet (no walletConnect) will be supported for the first version since the mobile wallets will be updated with web3ID-related features later.

**Comment by abizjak** [comment]
Initial version completed by #9
