### ISSUE TITLE
Issuer&Verifier text issues/improvements

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-web3id#91]
**Bug Description**
1. Add paragraph beneath the head title about what is the purpose of Concordia, why do we do this. Try to relate why is it necessary to pick minimum two attributes to get verified.
3. Title of the page is SoMe Verifier while should be Concordia
4. Text in the beginning missing "in" in "log in to the platform"
5. Add a text next to the Reveal name attribute something like: account on chain is required. Mainly because users could end up with Web3 credentials but without Mainnet account.

**Comment by soerenbf** [comment]
> **Bug Description**
> 
> 1. Add paragraph beneath the head title about what is the purpose of Concordia, why do we do this. Try to relate why is it necessary to pick minimum two attributes to get verified.

Will think about how to do this. I don't think the correct way is to just add a paragraph, but rather a link that opens something (probably a modal) which explains.
> 2. Title of the page is SoMe Verifier while should be Concordia

Changed (and removed the favicon as well.
> 3. Text in the beginning missing "in" in "log in to the platform"

Where do you mean? Can you post a screenshot?
> 4. Add a text next to the Reveal name attribute something like: account on chain is required. Mainly because users could end up with Web3 credentials but without Mainnet account.

I added text for this next to the attribute, but it doesn't look very nice. I think we should add a tooltip for this instead.

**Comment by abizjak** [comment]
![image](https://github.com/Concordium/concordium-web3id/assets/105212/2ff1257a-d06e-4aa1-a504-1d442891c687)


Regarding 3, see last line in the screenshot.
