### ISSUE TITLE
Issuing new credentials for the second time after verification was deleted and credentials revoked

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-web3id#96]
**Bug Description**
This is a case where verification was deleted and credentials revoked. Now, user wants to issue new credentials again.

**Steps to Reproduce**
1. Issue credentials and prove ownership.
2. After you have been verified, remove the verification and then revoke credentials.
3. Issue new credentials.

**Expected Result**
There should be an easy way for user to just issue new credentials.

**Actual Result**
User would need to remove part of the URL to be able to do that.

**Comment by mh-concordium** [comment]
What was the solution implemented?

**Comment by soerenbf** [comment]
The "Expected result" described in the issue should now be what happens.
